In [18]:
import pandas as pd
from pathlib import Path
id_table = pd.read_excel("/home/changbae/fmri_project/MDMR/notebook/data/id_table.xlsx")
demographics = pd.read_excel("/home/changbae/fmri_project/MDMR/notebook/data/demographics.xlsx")
log = pd.read_excel("/home/changbae/fmri_project/MDMR/notebook/data/log.xlsx")
scores_xls = pd.ExcelFile("/home/changbae/fmri_project/MDMR/notebook/data/scores.xlsx")
STAI_X_1 = scores_xls.parse("STAI_X_1")
STAI_X_2 = scores_xls.parse("STAI_X_2")
HADS = scores_xls.parse("HADS")
SWLS = scores_xls.parse("SWLS")
GAD_7 = scores_xls.parse("GAD_7")
PDSS = scores_xls.parse("PDSS")
LSAS = scores_xls.parse("LSAS")
MOCI = scores_xls.parse("MOCI")
BFNE = scores_xls.parse("BFNE")
PSWQ = scores_xls.parse("PSWQ")
HANDEDNESS_ = scores_xls.parse("HANDEDNESS_수정")

In [34]:
#fMRIPrep 1차 완료된 사람만 추출
directory_path = '/mnt/NAS2/data/SAD_gangnam_resting/fMRIPrep'
path = Path(directory_path)
fmri_code = []
# Iterate through the items in the directory
for item in path.iterdir():
    # Check if the item name starts with 'sub-' and does not end with '.html'
    if item.name.startswith('sub-') and not item.name.endswith('.html'):
        fmri_code.append(item.name[4:])

In [26]:
id_table

     Screening # Enrollment #      HAID ID  Subject #   이름
0              1     EXP-0001      0827jck          7  장찬경
1              2     EXP-0002       na0840          5  윤나예
2              3     EXP-0003     spwls915          4  조예진
3              4      HC-0001    wkddbswns          9  장윤준
4              5     EXP-0004      bje5409         12  박정은
..           ...          ...          ...        ...  ...
162          163     EXP-0089       bbclar        618  이아란
163          164     EXP-0090     john9987        597  최광묵
164          165     EXP-0091  jungminji57        608  정민지
165          166      HC-0075     gemma9em        609  김경미
166          167      HC-0076       yyyyjg        549  양정길

[167 rows x 5 columns]

In [31]:
#fMRIprep 1차 완료된 환자 code를 이용하여 screening #, enrollment #, HAID ID, 이름을 연결하는 파일을 만드는 함수
def generate_fmri_codes(id_table, fmri_code_list):
    # Create a copy of the dataframe to avoid modifying the original
    df = id_table.copy()
    
    # Define a function to generate fmri codes
    def generate_code(row):
        prefix = 's' if row['Enrollment #'].startswith('EXP') else 'c'
        code = f"{prefix}{int(row['Subject #']):04d}"
        return code
    
    # Apply the function to each row
    df['fmri_code'] = df.apply(generate_code, axis=1)
    
    # Filter the dataframe to include only rows where the fmri_code is in fmri_code_list
    df_filtered = df[df['fmri_code'].isin(fmri_code_list)]
    
    # Select relevant columns and rearrange them
    result = df_filtered[['fmri_code', 'Screening #', 'Enrollment #', 'HAID ID', '이름']]
    
    return result

result_df = generate_fmri_codes(id_table, fmri_code)

In [33]:
result_df.to_csv("/home/changbae/fmri_project/MDMR/notebook/data/id_lookup_table.csv")